apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-management-service
  template:
    metadata:
      labels:
        app: chat-management-service
    spec:
      containers:
        - name: app
          image: chat-management-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: "Never"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-management-service
spec:
  selector:
    app: chat-management-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
