apiVersion: v1
kind: ConfigMap
metadata:
  name: message-processing-service-config
  labels:
    app: message-processing-service
data:
  spring.data.mongodb.host: mongo
  spring.data.mongodb.url: "27017"
  spring.data.mongodb.database: chaticat
  spring.data.mongodb.username: mongo
  spring.data.mongodb.password: mongo
  kafka.address: http://kafka:9092
