apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-processing-service
  template:
    metadata:
      labels:
        app: message-processing-service
    spec:
      containers:
        - name: app
          image: message-processing-service:latest
          ports:
            - containerPort: 8083
          imagePullPolicy: "Never"
---
apiVersion: v1
kind: Service
metadata:
  name: message-processing-service
spec:
  selector:
    app: message-processing-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
