apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 48Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "volumes/data"