apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: app
          image: chat-service:latest
          ports:
            - containerPort: 8082
          imagePullPolicy: "Never"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: websocket
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
